USE [DBInvilliaDesafio]
GO

/****** Object:  Table [dbo].[Amigos]    Script Date: 09/21/2020 20:11:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Amigos](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Nome] [nchar](100) NOT NULL,
	[Apelido] [nchar](50) NULL,
	[Observacao] [text] NULL,
 CONSTRAINT [PK_Amigos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

