USE [master]
GO

/****** Object:  Database [DBInvilliaDesafio]    Script Date: 09/21/2020 20:10:15 ******/
CREATE DATABASE [DBInvilliaDesafio] ON  PRIMARY 
( NAME = N'DBInvilliaDesafio', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\DBInvilliaDesafio.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DBInvilliaDesafio_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\DBInvilliaDesafio_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DBInvilliaDesafio] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBInvilliaDesafio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBInvilliaDesafio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DBInvilliaDesafio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBInvilliaDesafio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBInvilliaDesafio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBInvilliaDesafio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBInvilliaDesafio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBInvilliaDesafio] SET  READ_WRITE 
GO

ALTER DATABASE [DBInvilliaDesafio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBInvilliaDesafio] SET  MULTI_USER 
GO

ALTER DATABASE [DBInvilliaDesafio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBInvilliaDesafio] SET DB_CHAINING OFF 
GO

